openapi: 3.0.3
info:
    title: Braver Backend API – Provisionnement et Patients
    version: 0.2.0
    description: >
        API consommée par le backend d'Ofys pour provisionner les professionnels et synchroniser des patients.

        ## Modèle de Sécurité

        L'API Backend utilise deux schémas d'authentification JWT:

        1. **providerJwt** (Fournisseur Ofys):
           - Utilisé UNIQUEMENT pour POST /clients
           - Identifie le fournisseur Ofys (pas une clinique spécifique)
           - Claims: iss, aud, sub (identifiant fournisseur), iat, exp

        2. **clinicJwt** (Clinique/Client):
           - Utilisé pour tous les autres endpoints
           - Identifie la clinique/client qui effectue la requête
           - Claims: iss, aud, tid (identifiant clinique), iat, exp

        Chaque requête doit inclure un JWT valide dans l'en-tête:
        ```
        Authorization: Bearer <JWT>
        ```

        Aucun endpoint public. Voir SECURITY.md pour la documentation complète du modèle de sécurité.
servers:
    - url: "<À préciser prochainement>"
      description: Production
    - url: "<À préciser prochainement>"
      description: Sandbox
tags:
    - name: Clients
    - name: Utilisateurs
    - name: Patients
security:
    - clinicJwt: []

paths:
    /clients:
        post:
            tags: [Clients]
            summary: Créer un nouveau client
            description: >
                Crée un nouveau client (clinique/organisation) avec ses lieux de pratique associés.
                Chaque client peut avoir plusieurs lieux de pratique (cliniques, pharmacies, services hospitaliers, etc.).

                **Sécurité**: Authentification requise (providerJwt)

                Note: Cet endpoint utilise providerJwt (identifiant le fournisseur Ofys) et non clinicJwt,
                car le client n'existe pas encore au moment de sa création.
            operationId: createClient
            security:
                - providerJwt: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ClientCreate'
            responses:
                '201':
                    description: Client créé
                    headers:
                        Location:
                            schema: { type: string }
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Client'
                '400': { description: Données invalides }
                '409': { description: Existe déjà }

    /utilisateurs:
        post:
            tags: [Utilisateurs]
            summary: Créer un professionnel confirmé (activation DSQ)
            description: >
                Notifie Braver qu'un professionnel confirmé (clé DSQ active) doit obtenir un accès.

                **Sécurité**: Authentification requise (clinicJwt)
            operationId: createUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserCreate'
            responses:
                '201':
                    description: Créé
                    headers:
                        Location:
                            schema: { type: string }
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                '400': { description: Données invalides }
                '409': { description: Existe déjà }

    /utilisateur/{id}:
        put:
            tags: [Utilisateurs]
            summary: Mettre à jour un professionnel
            description: >
                **Sécurité**: Authentification requise (clinicJwt)
            operationId: updateUser
            parameters:
                - $ref: '#/components/parameters/PathId'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserUpdate'
            responses:
                '200':
                    description: Mis à jour
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                '400': { description: Données invalides }
                '404': { description: Introuvable }
        delete:
            tags: [Utilisateurs]
            summary: Désactiver un professionnel (retirer l'accès)
            description: >
                **Sécurité**: Authentification requise (clinicJwt)
            operationId: deleteUser
            parameters:
                - $ref: '#/components/parameters/PathId'
            responses:
                '204': { description: Désactivé }
                '404': { description: Introuvable }

    /patients:
        post:
            tags: [Patients]
            summary: Créer un patient (profil démographique minimal confirmé)
            description: >
                Envoyer uniquement des dossiers complets (id, prénom, nom, dateNaissance, sexeNaissance, nam).

                **Sécurité**: Authentification requise (clinicJwt)
            operationId: createPatient
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PatientCreate'
            responses:
                '201':
                    description: Créé
                    headers:
                        Location:
                            schema: { type: string }
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Patient'
                '400': { description: Données invalides }
                '409': { description: Existe déjà }

    /patient/{id}:
        put:
            tags: [Patients]
            summary: Mettre à jour un patient
            description: >
                **Sécurité**: Authentification requise (clinicJwt)
            operationId: updatePatient
            parameters:
                - $ref: '#/components/parameters/PathId'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PatientUpdate'
            responses:
                '200':
                    description: Mis à jour
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Patient'
                '400': { description: Données invalides }
                '404': { description: Introuvable }
        delete:
            tags: [Patients]
            summary: Archiver un patient (décès, désassociation)
            description: >
                **Sécurité**: Authentification requise (clinicJwt)
            operationId: deletePatient
            parameters:
                - $ref: '#/components/parameters/PathId'
            responses:
                '204': { description: Archivé }
                '404': { description: Introuvable }

components:
    securitySchemes:
        providerJwt:
            type: http
            scheme: bearer
            bearerFormat: JWT
            description: >
                Jeton identifiant le fournisseur Ofys (pour créer des clients).
                Utilisé UNIQUEMENT pour POST /clients.
                Claims suggérés:
                - iss: émetteur Ofys
                - aud: "<installation URL à préciser>"
                - sub: identifiant du fournisseur Ofys
                - iat, exp
        clinicJwt:
            type: http
            scheme: bearer
            bearerFormat: JWT
            description: >
                Jeton backend identifiant la clinique (client).
                Claims suggérés:
                - iss: émetteur Ofys
                - aud: "<installation URL à préciser>"
                - tid: identifiant clinique/client
                - iat, exp
    parameters:
        PathId:
            name: id
            in: path
            required: true
            schema: { type: string }
            description: Identifiant Ofys de l'utilisateur/patient
    schemas:
        UserCreate:
            type: object
            required: [id, prenom, nom, professions, numeroPratique]
            properties:
                id: { type: string, description: Identifiant Ofys }
                prenom: { type: string }
                nom: { type: string }
                courriel:
                    type: string
                    format: email
                    nullable: true
                    description: Peut être ajouté plus tard au premier login
                genre:
                    type: string
                    nullable: true
                    enum: [M, F, O, NA]
                professions:
                    type: array
                    items: { type: string }
                    description: Valeurs fixes à convenir
                numeroPratique:
                    type: string
                    description: Issu des données DSQ
        UserUpdate:
            type: object
            properties:
                prenom: { type: string }
                nom: { type: string }
                courriel:
                    type: string
                    format: email
                    nullable: true
                genre:
                    type: string
                    nullable: true
                    enum: [M, F, O, NA]
                professions:
                    type: array
                    items: { type: string }
        User:
            allOf:
                - $ref: '#/components/schemas/UserCreate'

        PatientCreate:
            type: object
            required: [id, prenom, nom, dateNaissance, sexeNaissance, nam]
            properties:
                id: { type: string, description: Identifiant Ofys }
                prenom: { type: string }
                nom: { type: string }
                sexeNaissance:
                    type: string
                    nullable: true
                    enum: [M, F, O, NA]
                    description: Sexe à la naissance
                dateNaissance:
                    type: string
                    format: date
                nam:
                    type: string
                    description: Numéro d'assurance maladie
        PatientUpdate:
            type: object
            properties:
                prenom: { type: string }
                nom: { type: string }
                sexeActuel:
                    type: string
                    nullable: true
                    enum: [M, F, O, NA]
                    description: Sexe actuel
                courriel:
                    type: string
                    format: email
                    nullable: true
                nam:
                    type: string
                    description: Ne change qu'exceptionnellement
        Patient:
            allOf:
                - $ref: '#/components/schemas/PatientCreate'
                - type: object
                  properties:
                      braverPatientId:
                          type: string

        ClientCreate:
            type: object
            required: [id, nom]
            properties:
                id:
                    type: string
                    description: Identifiant unique du client côté Ofys
                nom:
                    type: string
                    description: Nom de la clinique/organisation
                lieux:
                    type: array
                    items: { $ref: '#/components/schemas/PracticeLocationCreate' }
                    description: Lieux de pratique associés au client

        Client:
            allOf:
                - $ref: '#/components/schemas/ClientCreate'
                - type: object
                  properties:
                      braverClientId:
                          type: string
                          description: Identifiant unique du client côté Braver

        PracticeLocationCreate:
            type: object
            required: [nom, typeLieu]
            properties:
                nom:
                    type: string
                    description: Nom du lieu de pratique
                typeLieu:
                    type: string
                    format: uuid
                    description: UUID du type de lieu (voir GET /typesLieux dans l'API frontend)
                rue:
                    type: string
                    nullable: true
                    description: Numéro et nom de la rue
                codePostal:
                    type: string
                    nullable: true
                    description: Code postal
                ville:
                    type: string
                    nullable: true
                    description: Ville/localité
                pays:
                    type: string
                    nullable: true
                    description: Pays (code ISO 3166-1 alpha-2 recommandé, ex. CH, FR)
                longitude:
                    type: number
                    format: double
                    nullable: true
                    description: Coordonnée géographique
                latitude:
                    type: number
                    format: double
                    nullable: true
                    description: Coordonnée géographique

        PracticeLocation:
            allOf:
                - $ref: '#/components/schemas/PracticeLocationCreate'
                - type: object
                  properties:
                      id:
                          type: string
                          description: Identifiant unique du lieu côté Braver
